blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(PostListView.as_view()), name='home'),
    path('create/', PostCreateView.as_view(), name='blog_form'),
    path('<slug:slug>/', PostDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', never_cache(PostUpdateView.as_view()), name='blog_update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='blog_confirm_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from mailing.apps import MailingConfig
from mailing.views import MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, toggle_status, \
    ClientListView, ClientDetailView, ClientCreateView, ClientUpdateView, ClientDeleteView, MailingLogListView

app_name = MailingConfig.name

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('create/', MailingCreateView.as_view(), name='mailing_create'),
    path('update/<int:pk>/', MailingUpdateView.as_view(), name='mailing_update'),
    path('delete/<int:pk>/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('toggle/<int:pk>/', toggle_status, name='toggle_status'),
    path('clients/', ClientListView.as_view(), name='client_list'),
    path('clients/detail/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('clients/update/<int:pk>/', ClientUpdateView.as_view(), name='client_update'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing_log/', MailingLogListView.as_view(), name='mailing_log_list')
]

mailing/models.py
from django.db import models

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    """Модель клиента"""
    name = models.CharField(max_length=150, verbose_name='Фамилия Имя Отчество')
    email = models.EmailField(unique=True, verbose_name='Почта')
    message = models.TextField(verbose_name='Комментарий', **NULLABLE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)
    is_active = models.BooleanField(default=True, verbose_name='Активность')

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'
        ordering = ('name',)

    def __str__(self):
        return f"{self.name} ({self.email})"


class Message(models.Model):
    """Модель сообщения для рассылки"""
    header = models.CharField(max_length=100, verbose_name='Тема письма')
    body = models.TextField(verbose_name='Тело письма')

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'
        ordering = ('header',)

    def __str__(self):
        return self.header


class Mailing(models.Model):
    """Модель рассылки"""

    FREQUENCY = [
        ('DAY', 'раз в день'),
        ('WEEK', 'раз в неделю'),
        ('MONTH', 'раз в месяц')
    ]

    STATUS = [
        ('FINISH', 'завершена'),
        ('CREATE', 'создана'),
        ('START', 'запущена')
    ]

    time = models.TimeField(auto_now_add=True, verbose_name='Время рассылки')
    create_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    frequency = models.CharField(max_length=100, choices=FREQUENCY, verbose_name='Периодичность')
    status = models.CharField(max_length=100, choices=STATUS, verbose_name='Статус')
    client = models.ManyToManyField(Client, verbose_name='Клиент', **NULLABLE)
    message = models.ForeignKey(Message, on_delete=models.SET_NULL, verbose_name='Сообщение', **NULLABLE)
    finish_date = models.DateField(verbose_name='Дата завершения рассылки', default='2024-01-01')
    finish_time = models.TimeField(verbose_name='Время завершения рассылки', default='00:00')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE)
    is_published = models.BooleanField(default=True, verbose_name='Опубликован')

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'
        ordering = ('time',)

    def __str__(self):
        return f'Рассылка №{self.pk}'

    def delete(self, *args, **kwargs):
        """Функция, делающая пост не активным"""
        self.is_published = False
        self.status = 'FINISH'
        self.save()


class MailingLogs(models.Model):
    """Модель логов рассылки"""
    STATUS = [
        ('Success', 'успешно'),
        ('Failure', 'отказ')
    ]

    data_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки')
    status = models.CharField(max_length=100, choices=STATUS, verbose_name='Статус попытки')
    server_response = models.TextField(verbose_name='Ответ почтового сервера', **NULLABLE)
    mailing = models.ForeignKey(Mailing, on_delete=models.SET_NULL, verbose_name='Рассылка', **NULLABLE)

    class Meta:
        verbose_name = 'лог отправки письма'
        verbose_name_plural = 'логи отправок писем'

    def __str__(self):
        return f'Лог {self.pk}'

mailing/forms.py
from django import forms

from mailing.models import Client, Mailing


class FormStyleMixin:
    """Класс-миксин для стилизации форм"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(FormStyleMixin, forms.ModelForm):
    """Форма для создания и редактирования поста"""

    class Meta:
        model = Client
        exclude = ('is_active', 'user')


class MailingForm(FormStyleMixin, forms.ModelForm):
    """Форма для создания и редактирования рассылки"""

    class Meta:
        model = Mailing
        exclude = ('is_active', 'user', 'status', 'is_published')

mailing/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from mailing.forms import ClientForm, MailingForm
from mailing.models import Mailing, Client, MailingLogs
from mailing.services import MessageService, delete_task, send_mailing


class MailingListView(LoginRequiredMixin, generic.ListView):
    """Представление для просмотра рассылок"""
    model = Mailing
    extra_context = {'title': 'Рассылки'}

    def get_queryset(self):
        """Функция, позволяющая просматривать только свои рассылки для пользователя, который не является менеджером"""
        user = self.request.user
        if user.is_superuser or user.is_staff:
            queryset = Mailing.objects.all()
        else:
            queryset = Mailing.objects.filter(user=user)

        queryset = queryset.filter(is_published=True)
        return queryset


class MailingCreateView(LoginRequiredMixin, generic.CreateView):
    """Представление для создание рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')

    def get_queryset(self):
        """Позволяет создавать рассылки только для своих клиентов"""
        user = self.request.user
        mailing = Mailing.objects.all()
        if user.is_staff or user.is_superuser:
            queryset = mailing
        else:
            queryset = mailing.client.filter(user=user, is_active=True)
        return queryset

    def form_valid(self, form):
        """Если форма валидна, то при создании рассылки запускается периодическая задача и изменяется статус рассылки"""
        mailing = form.save(commit=False)
        mailing.user = self.request.user
        mailing.status = 'CREATE'
        mailing.save()

        message_service = MessageService(mailing)
        send_mailing(mailing)
        message_service.create_task()
        mailing.status = 'START'
        mailing.save()

        return super(MailingCreateView, self).form_valid(form)


class MailingUpdateView(LoginRequiredMixin, generic.UpdateView):
    """Представление для изменения рассылки"""
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailing:mailing_list')


class MailingDeleteView(LoginRequiredMixin, generic.DeleteView):
    """Представление для удаления рассылки"""
    model = Mailing
    success_url = reverse_lazy('mailing:mailing_list')


def toggle_status(request, pk):
    """Функция, позволяющая отключать и активировать рассылку"""
    mailing = get_object_or_404(Mailing, pk=pk)
    message_service = MessageService(mailing)
    if mailing.status == 'START' or mailing.status == 'CREATE':
        delete_task(mailing)
        mailing.status = 'FINISH'
    else:
        message_service.create_task()
        mailing.status = 'START'

    mailing.save()

    return redirect(reverse('mailing:mailing_list'))


class ClientListView(LoginRequiredMixin, generic.ListView):
    """Представление для просмотра клиентов"""
    model = Client
    extra_context = {'title': 'Клиенты'}

    def get_queryset(self):
        """Функция, позволяющая просматривать только своих клиентов для пользователя, который не является менеджером"""
        user = self.request.user
        if user.is_staff or user.is_superuser:
            queryset = Client.objects.all()
        else:
            queryset = Client.objects.filter(user=user)

        queryset = queryset.filter(is_active=True)
        return queryset


class ClientDetailView(LoginRequiredMixin, generic.DetailView):
    """Представление для просмотра конкретного клиента"""
    model = Client


class ClientCreateView(LoginRequiredMixin, generic.CreateView):
    """Представление для создания клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')

    def form_valid(self, form):
        client = form.save(commit=False)
        client.user = self.request.user
        client.save()
        return super(ClientCreateView, self).form_valid(form)


class ClientUpdateView(LoginRequiredMixin, generic.UpdateView):
    """Представление для изменения клиента"""
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:client_list')


class ClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    """Представление для удаления клиента"""
    model = Client
    success_url = reverse_lazy('mailing:client_list')
    permission_required = 'mailing.delete_client'


class MailingLogListView(LoginRequiredMixin, generic.ListView):
    """Представление для просмотра всех попыток рассылок"""
    model = MailingLogs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = "Попытки рассылки"
        context['log_list'] = MailingLogs.objects.all()
        return context

mailing/templates/mailing/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SkyChimp</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
{%include 'mailing/includes/inc_catalog_menu.html' %}
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>

{% include 'mailing/includes/inc_catalog_footer.html' %}
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/client_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            Уверены что хотите заблокировать клиента {{ client.name }}
            <input type="submit" class="btn btn-success" value="Уверен">
        </div>
    </form>
    <a href="{% url 'mailing:client_list' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
{% endblock %}

mailing/templates/mailing/client_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="table">
    <table>
        <tr>
            <h2>{{ client.name }}</h2>
            <h3>{{client.email}}</h3>
        </tr>
    </table>
</div>

{% if client.user == user %}
<div class="container">
    <a href='{% url "mailing:client_update" client.pk %}' class="btn btn-secondary my-3"
       style="background: darkgreen">Изменить</a>

    {% endif %}

    {% if perms.mailing.delete_client or client.user == user %}
    <a href='{% url "mailing:client_delete" client.pk %}' class="btn btn-secondary my-3"
       style="background: red">Заблокировать</a>
</div>
{% endif %}

<div class="container">
    <a href='{% url "mailing:client_list" %}' class="btn btn-secondary my-3"
       style="background: blue">Назад</a>
</div>

{% endblock %}

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            {{ form.as_p }}
            <input type="submit" class="btn btn-success" value="Сохранить">
        </div>
    <a href="{% url 'mailing:client_list' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
    </form>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="table">
    <table>
        {% for client in client_list %}
        <tr>
            <td>
                <a style="color: black" class="btn" href="{% url 'mailing:client_detail' client.pk %}">
                    {{ client.name }}</a>
            </td>
            <td>
                {{client.email}}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>

<div class="container">
    <a href='{% url "mailing:client_create" %}' class="btn btn-secondary my-3"
       style="background: darkgreen">Добавить</a>
</div>

{% endblock %}

mailing/templates/mailing/mailing_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            Уверены что хотите удалить рассылку {{ mailing }}
            <input type="submit" class="btn btn-success" value="Уверен">
        </div>
    </form>
    <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
{% endblock %}

mailing/templates/mailing/mailing_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<form class="obratnuj-zvonok" autocomplete="off" method='post'>
    {% csrf_token %}
    <div class="container">
        {{ form.as_p }}
        {% if user.is_authenticated%}
        <input type="submit" class="btn btn-success" value="Сохранить">
        {% endif %}
    </div>
    <a href="{% url 'mailing:mailing_list' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
</form>
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}
{% for mailing in mailing_list %}
<div class="my-3 p-3 bg-white rounded box-shadow">

    {% if mailing.user == user or user.is_superuser %}
    <a href="{% url 'mailing:mailing_update' mailing.pk %}" class="border-bottom border-gray pb-2 mb-0">
        {{ mailing }}</a>
    {% else %}
    <a href="#" class="border-bottom border-gray pb-2 mb-0">{{ mailing }}</a>
    {% endif %}

    <div class="media text-muted pt-3">
        <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
            <strong class="d-block text-gray-dark">Периодичность: {{ mailing.frequency }}</strong>
            <strong class="d-block text-gray-dark">Статус: {{ mailing.status }}</strong>
        </p>
    </div>

    {% if user.is_staff or user == mailing.user %}
    <a href="{% url 'mailing:mailing_delete' mailing.pk %}" class="btn btn-secondary"
       style="background: red">Удалить</a>
    {% endif %}

    {% if user.is_staff or user == mailing.user %}
    <a href="{% url 'mailing:toggle_status' mailing.pk %}" class="btn btn-secondary"
       style="background: blue">
        {% if mailing.status == 'FINISH' %}
        Активировать
        {% else %}
        Отключить
        {% endif %}
    </a>
    {% endif %}
</div>
{% endfor %}

{% if user.is_authenticated %}
<div class="container">
    <a href="{% url 'mailing:mailing_create' %}" class="btn btn-secondary my-3"
       style="background: darkgreen">Создать</a>
{% endif %}
</div>
{% endblock %}

mailing/templates/mailing/mailinglogs_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="table">
    <table>
        <tr>
            <td>
                Время рассылки
            </td>
            <td>
                Рассылка
            </td>
            <td>
                Статус
            </td>
        </tr>
        {% for log in log_list %}
        <tr>
            <td>
                {{ log.data_time }}
            </td>
            <td>
                {{log.mailing}}
            </td>
            <td>
                {{ log.status }}
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}