blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(PostListView.as_view()), name='home'),
    path('create/', PostCreateView.as_view(), name='blog_form'),
    path('<slug:slug>/', PostDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', never_cache(PostUpdateView.as_view()), name='blog_update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='blog_confirm_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse


NULLABLE = {'blank': True, 'null': True}


class Post(models.Model):
    """Модель описывающая пост в блоге"""
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    slug = models.SlugField(max_length=150, verbose_name='Slug', **NULLABLE)
    content = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='blog/', verbose_name='Изображение', **NULLABLE)
    create_date = models.DateField(auto_now_add=True, verbose_name='Дата создания')
    is_published = models.BooleanField(default=True, verbose_name='Опубликован')
    count_of_view = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')

    def delete(self, *args, **kwargs):
        """Функция, делающая пост не активным"""
        self.is_published = False
        self.save()

    def __str__(self):
        return f'{self.title}'

    def increase_count_of_view(self):
        """Увеличивает счетчик просмотров на 1"""
        self.count_of_view += 1
        self.save()

    def get_absolute_url(self):
        return reverse('blog_detail', kwargs={'slug': self.slug})

    class Meta:
        verbose_name = 'новость'
        verbose_name_plural = 'новости'
        ordering = ('title',)

blog/forms.py
from django import forms

from blog.models import Post
from mailing.forms import FormStyleMixin


class PostForm(FormStyleMixin, forms.ModelForm):
    """Форма для создания поста в блоге"""

    class Meta:
        model = Post
        exclude = ('slug', 'is_published', 'count_of_view')

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views import generic
from django.utils.text import slugify
from transliterate import translit
from blog.forms import PostForm
from blog.models import Post
from blog.services import get_cache_detail_post


class PostListView(generic.ListView):
    """Представление для просмотра всех постов"""
    model = Post
    extra_context = {
        "title": "Лучшие загородные отели Санкт-Петербурга"
    }

    def get_queryset(self):
        """Просмотр только активных постов"""
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class PostDetailView(generic.DetailView):
    """Представление для просмотра каждого поста"""
    model = Post
    queryset = get_cache_detail_post()

    def get_object(self, queryset=None):
        """Возвращает обьект поста с увеличенным количеством просмотров на 1 при переходе на страницу поста"""
        object_item = super().get_object(queryset)
        object_item.increase_count_of_view()
        object_item.save()
        return object_item


class PostCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    """Представление для создания поста, которое доступно только для контент-менеджера"""
    model = Post
    form_class = PostForm
    success_url = reverse_lazy('blog:home')
    permission_required = 'blog.add_post'

    def form_valid(self, form):
        """Для валидного поста присваивается slug"""
        post = form.save(commit=False)
        eng_title = translit(post.title, 'ru', reversed=True)
        post.slug = slugify(eng_title, allow_unicode=True)
        return super(PostCreateView, self).form_valid(form)


class PostUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    """Представление для изменения поста"""
    model = Post
    form_class = PostForm
    permission_required = 'blog.change_post'

    def get_success_url(self):
        """При успешном изменение редиректит на страницу поста"""
        return reverse('blog:blog_detail', kwargs={'slug': self.object.slug})


class PostDeleteView(LoginRequiredMixin, PermissionRequiredMixin, generic.DeleteView):
    """Представление для удаления поста"""
    model = Post
    success_url = reverse_lazy('blog:home')
    permission_required = 'blog.delete_post'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset

blog/templates/blog/post_confirm_delete.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            Уверены что хотите удалить новость {{ blog }}
            <input type="submit" class="btn btn-success" value="Уверен">
        </div>
    </form>
    <a href="{% url 'blog:home' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
{% load tags %}

<div class="container">
    <div class="row featurette">
        <div class="col-md-7">
            <h2>{{ post.title }}</h2>
            <p class="lead">{{ post.content }}</p>
        </div>
        <div class="col-md-5">
            <img width="350" height="300" class="featurette-image img-fluid mx-auto" src="/media/{{ post.image }}">
        </div>
    </div>
</div>
<div>
    <a href="{% url 'blog:home' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>

    {% if perms.blog.change_post %}
    <a href="{% url 'blog:blog_update' post.pk %}" class="btn btn-secondary my-3"
       style="background: green">Изменить</a>
    <a href="{% url 'blog:blog_confirm_delete' post.pk %}" class="btn btn-secondary my-3"
       style="background: red">Удалить</a>
    {% endif %}

</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <form class="obratnuj-zvonok" autocomplete="off" method='post'>
        {% csrf_token %}
        <div class="container">
            {{ form.as_p }}
            <input type="submit" class="btn btn-success" value="Сохранить">
        </div>
    <a href="{% url 'blog:home' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'mailing/base.html' %}

{% block content %}

    {% for post in post_list %}
        {% include 'blog/includes/inc_post_card.html' %}
    {% endfor %}

<div class="container">

    {% if perms.blog.add_post %}
    <a href="{% url 'blog:blog_form' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Создать</a>
    {% endif %}

</div>
{% endblock %}