blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(PostListView.as_view()), name='home'),
    path('create/', PostCreateView.as_view(), name='blog_form'),
    path('<slug:slug>/', PostDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', never_cache(PostUpdateView.as_view()), name='blog_update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='blog_confirm_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from django.views.generic import TemplateView
from users.apps import UsersConfig
from users.views import ProfileUpdateView, RegisterView, EmailVerify, CustomPasswordResetView, \
    CustomPasswordResetConfirmView, CustomPasswordResetDoneView, CustomPasswordResetCompleteView

app_name = UsersConfig.name
urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileUpdateView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('password/reset/', CustomPasswordResetView.as_view(template_name='users/password_reset_form.html'),
         name='password_reset'),
    path('confirm_email/', TemplateView.as_view(template_name='users/confirm_email.html'), name='confirm_email'),
    path('verify_email/<uidb64>/<token>/', EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify'),
    path('password/reset/confirm/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password/reset/done', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete')
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from mailing.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    first_name = models.CharField(max_length=100, verbose_name='Имя')
    last_name = models.CharField(max_length=100, verbose_name='Фамилия')
    middle_name = models.CharField(max_length=100, verbose_name='Отчество', **NULLABLE)
    message = models.TextField(verbose_name='Комментарий', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, SetPasswordForm, PasswordResetForm
from django import forms
from django.utils.translation import gettext_lazy as _

from mailing.forms import FormStyleMixin
from users.models import User


class UserForm(FormStyleMixin, UserChangeForm):
    """Форма для профиля пользователя"""

    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'middle_name', 'message')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()


class UserRegisterForm(FormStyleMixin, UserCreationForm):
    """Форма для регистрации пользователя"""

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class CustomPasswordResetForm(FormStyleMixin, PasswordResetForm):
    """Форма для сброса пароля"""
    email = forms.EmailField(
        label=_("Email"),
        max_length=50,
        widget=forms.EmailInput(attrs={"autocomplete": "email"}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    class Meta:
        model = User


class PasswordResetConfirmForm(FormStyleMixin, SetPasswordForm):
    """Форма для обновления пароля"""

    class Meta:
        model = User

users/views.py
from django.contrib.auth import login
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordResetConfirmView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetCompleteView
from django.core.exceptions import ValidationError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.http import urlsafe_base64_decode
from django.views import generic
from config import settings
from users.forms import UserForm, UserRegisterForm, PasswordResetConfirmForm, CustomPasswordResetForm
from users.models import User
from users.services.email_send_verify import send_mail_for_verify


class ProfileUpdateView(generic.UpdateView):
    """Представление для изменения данных пользователя"""
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class RegisterView(generic.CreateView):
    """Представление для регистрации пользователя"""
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('users:confirm_email')

    def form_valid(self, form):
        """Отправка сообщения для верификации"""
        response = super().form_valid(form)
        user = form.save()
        # отправка сообщения для подтверждения электронной почты
        send_mail_for_verify(self.request, user)
        return response


class EmailVerify(generic.View):
    """Представление для верификации"""

    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        # проверка что токен сброса пароля верен для данного пользователя
        if user is not None and default_token_generator.check_token(user, token):
            user.save()
            login(request, user)
            return redirect('users:login')
        return redirect('users:invalid_verify')

    @staticmethod
    def get_user(uidb64):
        """Получение пользователя по uid"""
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist, ValidationError):
            user = None
        return user


class CustomPasswordResetView(PasswordResetView):
    """Восстановление пароля"""
    template_name = 'users/password_reset_form.html'
    form_class = CustomPasswordResetForm
    success_url = reverse_lazy('users:password_reset_done')
    email_template_name = 'users/email_reset.html'
    from_email = settings.EMAIL_HOST_USER


class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    """Подтверждение сброса пароля"""
    form_class = PasswordResetConfirmForm
    template_name = 'users/password_reset_confirm.html'
    success_url = reverse_lazy('users:password_reset_complete')


class CustomPasswordResetDoneView(PasswordResetDoneView):
    """Выполнение сброса пароля"""
    template_name = 'users/password_reset_done.html'


class CustomPasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'blog/blog_list.html'

users/templates/users/confirm_email.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class='row'>
    Пожалуйста, проверьте свою почту для дальнейшей регистрации
    </div>
{% endblock %}

users/templates/users/email_reset.html
Cброс пароля для электронной почты {{ email }}.
Перейдите по ссылке ниже:
{{ protocol }}://89.108.98.89 {% url 'users:password_reset_confirm' uidb64=uid token=token %}

users/templates/users/invalid_verify.html
{% extends 'catalog/base.html' %}

{% block content %}
        Ваша ссылка не корректна, попробуйте зарегистрироваться снова
{% endblock %}

users/templates/users/login.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="col-3">
        <div class="col-6">
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Войти</button>
                    <a type="sudmit" href={% url 'users:password_reset'%}>Забыли пароль?</a>
                </form>
            </div>
        </div>
    </div
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'mailing/base.html' %}

{% block content %}
    {% if validlink %}
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" class="btn btn-success" value="Изменить пароль"/></p>
        </form>
    {% else %}
        <p>Ваша ссылка не корректна, попробуйте снова</p>
    {% endif %}
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class='row'>
    Пожалуйста, проверьте свою почту для восстановления пароля
    </div>
{% endblock %}

users/templates/users/password_reset_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <div class="col-6">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Далее</button>
                </form>
            </div>
            <div class="card-header"></div>
        </div>
    </div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailing/base.html' %}

{% block content %}
    <div class="container">
        <div class="col-6">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% if not user.is_authenticated %}
                        <button type="submit" class="btn btn-success">Зарегистрироваться</button>
                    {% else %}
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    {% endif %}
                </form>
            </div>
            <a href="{% url 'blog:home' %}" class="btn btn-secondary my-3"
       style="background: #0062cc">Назад</a>
        </div>
    </div>
{% endblock %}

users/templates/users/verify_email.html
{% autoescape off %}
Добрый день, {{ user.get_username }}
    Для завершения регистрации необходимо перейти по ссылке:
http://89.108.98.89{% url 'users:verify_email' uidb64=uid token=token %}


{% endautoescape %}