blog/urls.py
from django.urls import path
from django.views.decorators.cache import never_cache, cache_page

from blog.apps import BlogConfig
from blog.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60)(PostListView.as_view()), name='home'),
    path('create/', PostCreateView.as_view(), name='blog_form'),
    path('<slug:slug>/', PostDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', never_cache(PostUpdateView.as_view()), name='blog_update'),
    path('delete/<int:pk>/', PostDeleteView.as_view(), name='blog_confirm_delete')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('mailing/', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main.apps import MainConfig
from main.views import IndexView

app_name = MainConfig.name

urlpatterns = [
    path('', IndexView.as_view(template_name='main/index.html'), name='index')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from random import sample
from django.views.generic import TemplateView
from blog.models import Post
from main.services import get_count_mailing, get_active_mailing, get_unique_clients


class IndexView(TemplateView):
    """Представление главной страницы сервиса"""
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        all_posts = list(Post.objects.filter(is_published=True))
        context['random_post'] = sample(all_posts, min(3, len(all_posts)))
        context['count_mailing'] = get_count_mailing()
        context['active_mailing'] = get_active_mailing()
        context['unique_clients'] = get_unique_clients()

        return context

main/templates/main/index.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="table">
    <table>
        <tr>
            <td>
                Количество рассылок всего
            </td>
            <td>
                {{count_mailing}}
            </td>
        </tr>
        <tr>
            <td>
                Количество активных рассылок:
            </td>
            <td>
                {{active_mailing}}
            </td>
        </tr>
        <tr>
            <td>
                Количество уникальных клиентов для рассылок:
            </td>
            <td>
                {{unique_clients}}
            </td>
        </tr>
    </table>
</div>

{% load tags %}
{% for post in random_post %}
<div class="table">
    <div class="row mb-2">
        <div class="col-6">
            <div class="card flex-md-row mb-4 box-shadow h-md-250">
                <div class="card-body d-flex flex-column align-items-start">
                    <small class="text-muted">👁 {{ post.count_of_view }}</small>
                    <h5 class="mb-0">
                        <a class="text-dark">{{ post.title }}</a>
                    </h5>
                    <div class="mb-1 text-muted">{{ post.create_date }}</div>
                    <p class="card-text mb-auto">{{ post.content | truncatechars:100 }}</p>
                    <a href="{% url 'blog:blog_detail' post.slug %}">Подробнее</a>
                </div>
                <img class="card-img-right flex-auto d-none d-md-block" src={% mediapath post.image %} width="250"
                     height="200">
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}